# Task 1: Python Proficiency Check – AI Bootcamp Prep

## Section 1: Basics & Control Flow

### **Task 1**: FizzBuzz with a Twist

*Instruction*: Write a function that prints numbers from 1 to 50. For multiples of 3, print "AI", for multiples of 5 print "Bootcamp", and for multiples of both 3 and 5 print "AI Bootcamp".

In [ ]:
def fizzbuzz_ai_bootcamp():
  for i in range (1,51):
    if i%3==0 and i%5==0:
      print(f"{i}=AI BOOTCAMP")
    elif i%5==0:
      print(f"{i}=BOOTCAMP")
    elif i%3==0:
      print(f"{i}=AI")
    else:
      print(i)
fizzbuzz_ai_bootcamp()

1
2
3=AI
4
5=BOOTCAMP
6=AI
7
8
9=AI
10=BOOTCAMP
11
12=AI
13
14
15=AI BOOTCAMP
16
17
18=AI
19
20=BOOTCAMP
21=AI
22
23
24=AI
25=BOOTCAMP
26
27=AI
28
29
30=AI BOOTCAMP
31
32
33=AI
34
35=BOOTCAMP
36=AI
37
38
39=AI
40=BOOTCAMP
41
42=AI
43
44
45=AI BOOTCAMP
46
47
48=AI
49
50=BOOTCAMP


### **Task 2**: List Comprehensions and Functions

*Instruction*: Given a list of numbers, square only the even numbers using a list comprehension and define a function that returns the result.

In [ ]:
def square_evens(numbers):
    for i in numbers:
        if i%2==0:
            print("square root of ",i," = ",i**2)
        else:
            print()
print(square_evens([1, 2, 3, 4, 5, 6]))


square root of  2  =  4

square root of  4  =  16

square root of  6  =  36
None


## Section 2: Data Structures & File I/O

### **Task 3**: Word Frequency from a File

*Instruction*: Read the provided text file (sample.txt) and return the 5 most common words (ignoring punctuation and case).

In [ ]:
from collections import Counter
import string
def top_5_words(filepath):
  with open(filepath,'r') as file:
    text=file.read()
  text= text.lower()
  text=text.translate(str.maketrans('', '', string.punctuation))
  words = text.split()
  word_counts = Counter(words)
  most_common = word_counts.most_common(5)
  for word, count in most_common:
    print(f"{word}: {count}")


top_5_words('/content/sample_data/README.md')


is: 4
a: 3
the: 3
sample: 2
at: 2


## Section 3: NumPy & pandas

### **Task 4**: NumPy Matrix Magic

*Instruction*: Create a 5x5 matrix with random integers from 1 to 10. Replace all elements greater than 5 with 0.

In [ ]:
import numpy as np

def matrix_transform():
    matrix1=np.random.randint(1,11,size=(5,5))
    print("Original matrix = ")
    print(matrix1)
    matrix1 [matrix1>5]=0
    print()
    print("New matrix = ")
    print(matrix1)
matrix_transform()

Original matrix = 
[[8 3 9 8 3]
 [7 9 1 1 3]
 [1 7 3 8 4]
 [4 6 5 7 1]
 [9 9 5 6 1]]

New matrix = 
[[0 3 0 0 3]
 [0 0 1 1 3]
 [1 0 3 0 4]
 [4 0 5 0 1]
 [0 0 5 0 1]]


### **Task 5**: pandas DataFrame Manipulation

*Instruction*: Given the following dictionary, convert it into a DataFrame, calculate the average score per student, and add it as a new column.

## Section 4: Visualization & Logic

In [12]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Math': [85, 78, 92],
    'Science': [90, 88, 84],
    'English': [87, 85, 80]
}

df=pd.DataFrame(data)
df["Average"]=df[["Math","Science","English"]].mean(axis=1)
print(df)

      Name  Math  Science  English    Average
0    Alice    85       90       87  87.333333
1      Bob    78       88       85  83.666667
2  Charlie    92       84       80  85.333333


### **Task 6**: Simple Data Visualization

*Instruction*: Use matplotlib to create a bar chart showing the average score per subject from the DataFrame in the previous task.

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Math': [85, 78, 92],
    'Science': [90, 88, 84],
    'English': [87, 85, 80]
}

df = pd.DataFrame(data)
df["Average"] = df[["Math", "Science", "English"]].mean(axis=1)

# Calculate average score per subject
average_scores = df[['Math', 'Science', 'English']].mean()

# Create bar chart
plt.bar(average_scores.index, average_scores.values)
plt.xlabel("Subject")
plt.ylabel("Average Score")
plt.title("Average Score per Subject")
plt.show()


## Section 5: Mini-Project Challenge

### **Task 7**: Build a Mini Calculator with Exception Handling

*Instruction*: Write a function that takes two numbers and an operator as input (+, -, *, /). Return the result, and handle divide-by-zero and invalid operator cases with appropriate error messages.

In [19]:
def calculator(a, b, operator):
    try:
        if operator == '+':
            result = a + b
        elif operator == '-':
            result = a - b
        elif operator == '*':
            result = a * b
        elif operator == '/':
            result = a / b
        else:
            raise ValueError("Invalid operator. Please use +, -, *, or /.")
        return result
    except ZeroDivisionError:
        return "Error: Cannot divide by zero."
    except ValueError as e:
        return f"Error: {e}"


print(calculator(10, 5, '+'))  # Output: 15
print(calculator(10, 2, '/'))  # Output: Error: Cannot divide by zero.

15
5.0
